import type { Metadata } from "next";
import {Inter ,   Miniver } from "next/font/google";
import { Great_Vibes } from "next/font/google"; 

import "./globals.css";
import Header from "@/components/landing page/Header";
import Footer from "@/components/landing page/Footer";
import { SheetDemo } from "./sheet";

const inter =Inter
({
  subsets: ['latin'],
  weight:['400' , '700']

})
 
const greatVibes = Great_Vibes
({
  subsets: ['latin'],
  weight:['400' ]

})

const miniver = Miniver
({
  subsets: ['latin'],
  weight:['400' ]

})





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        {/* Set a fixed viewport width */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className = "font-sans"
      > 
    <div className="main-container">
      
       
      <main>
       
    <SheetDemo/>
      <Header/>
        {children}
      </main>
 
         <Footer/>
         </div> 
      </body>
    </html>
  );
}
